### ISSUE TITLE
Jetbrains fails with PKI cert error when connecting to deploy with self-signed certs

### ISSUE THREAD

**Issue by ericpaulsen** [coder/jetbrains-coder#242]
two air-gapped customers who are using their own self-signed certs attempted to use Gateway `2023.1.1` and Coder plugin `2.3.0` and received the following error:

```
Failed to configure connection to https://coder.enterprise.dev/: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309
                at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
                at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
                at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
                at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
                at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
                at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
                at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
                at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
                at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
                at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
                at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
           at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
                at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
                at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
                at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at com.coder.gateway.sdk.CoderRestClientService$initClientSession$$inlined$-addInterceptor$2.intercept(OkHttpClient.kt:1080)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at com.coder.gateway.sdk.CoderRestClientService$initClientSession$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1080)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
                at com.coder.gateway.sdk.CoderRestClientService.initClientSession(CoderRestClientService.kt:58)
                at com.coder.gateway.views.steps.CoderWorkspacesStepView.authenticate(CoderWorkspacesStepView.kt:626)
                at com.coder.gateway.views.steps.CoderWorkspacesStepView.access$authenticate(CoderWorkspacesStepView.kt:100)
                at com.coder.gateway.views.steps.CoderWorkspacesStepView$connect$1.invokeSuspend(CoderWorkspacesStepView.kt:467)
                at com.coder.gateway.views.steps.CoderWorkspacesStepView$connect$1.invoke(CoderWorkspacesStepView.kt)
                at com.coder.gateway.views.steps.CoderWorkspacesStepView$connect$1.invoke(CoderWorkspacesStepView.kt)
                at com.intellij.openapi.rd.util.ProgressCoroutineScope$execute$2.invokeSuspend(BackgroundProgressCoroutineUtil.kt:227)
                at com.intellij.openapi.rd.util.ProgressCoroutineScope$execute$2.invoke(BackgroundProgressCoroutineUtil.kt)
                at com.intellij.openapi.rd.util.ProgressCoroutineScope$execute$2.invoke(BackgroundProgressCoroutineUtil.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
                at com.intellij.openapi.rd.util.ProgressCoroutineScope.execute$intellij_platform_rd_community(BackgroundProgressCoroutineUtil.kt:226)
                at com.intellij.openapi.rd.util.BackgroundProgressCoroutineUtilKt$launchUnderBackgroundProgress$1$1.invokeSuspend(BackgroundProgressCoroutineUtil.kt:64)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:172)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:168)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:158)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createBackgroundable$1$1.run(BackgroundProgressCoroutineUtil.kt:191)
                at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
                at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
                at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
                at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
                at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                atjava.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
                at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
                at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
                at java.base/sun.security.validator.Validator.validate(Validator.java:264)
                at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
                at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
                at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
                ... 83 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
                at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
                at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
                at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
                ... 88 more
```

**Comment by ericpaulsen** [comment]
this is closed now that we have documented troubleshooting steps:
