### ISSUE TITLE
receiving jstack error when downloading the IDE binary

### ISSUE THREAD

**Issue by ericpaulsen** [coder/jetbrains-coder#253]
using Gateway `2023.1.2` and plugin version `2.3.0`

here's the output:

```
The following exception failed the deployment

com.jetbrains.gateway.ssh.deploy.DeployException:

Details:
An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/d981d9ef7a491_ideaIU-2023.1.2 --project-path=/home/coder/coder'
Exit code: 1
               at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:280)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:172)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:168)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:158)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createModal$1$1.run(BackgroundProgressCoroutineUtil.kt:203)
                at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)

                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604) 
                at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
                at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
                at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
                at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
                at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException:

Details:
An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/d981d9ef7a491_ideaIU-2023.1.2 --project-path=/home/coder/coder'
Exit code: 1
                at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:275)
                ... 35 more
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException:
Details:
An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/d981d9ef7a491_ideaIU-2023.1.2 --project-path=/home/coder/coder'
Exit code: 1
                at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:273)
                ... 35 more
Caused by: com.jetbrains.gateway.ssh.RemoteCommandException:

Details:
An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/d981d9ef7a491_ideaIU-2023.1.2 --project-path=/home/coder/coder'
Exit code: 1
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.anErrorOccurred(GoHighLevelHostAccessor.kt:184)
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.callAndReportError(GoHighLevelHostAccessor.kt:173)
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.access$callAndReportError(GoHighLevelHostAccessor.kt:29)
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor$callAndReportError$1.invokeSuspend(GoHighLevelHostAccessor.kt)
                ... 35 more
==== ENVIRONMENT ====

INSTALLED PRODUCTS
                IntelliJ IDEA         231.9011.34
AVAILABLE MEMORY
                 3.76GB

==== DIAGNOSTIC ERRORS ====

Could not get host jstack:

Details:

An error occurred while executing command: 'get-jstack --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/d981d9ef7a491_ideaIU-2023.1.2 --project-path=/home/coder/coder'

Exit code: 1
```

**Comment by adrianbpa** [comment]
I am encountering the same issue when connecting remotely to GitHub Codespaces using Gateway and Rider for C#:

```
==== FAILURES ====

The following exception failed the deployment
com.jetbrains.gateway.ssh.deploy.DeployException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/workspaces/.codespaces/shared/editors/jetbrains/JetBrainsRider-2023.1 --project-path=/workspaces/prj-name/PrjName.sln'
Exit code: 1
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:253)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:172)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:168)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:158)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createModal$1$1.run(BackgroundProgressCoroutineUtil.kt:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/workspaces/.codespaces/shared/editors/jetbrains/JetBrainsRider-2023.1 --project-path=/workspaces/prj-name/PrjName.sln'
Exit code: 1
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:248)
	... 35 more
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/workspaces/.codespaces/shared/editors/jetbrains/JetBrainsRider-2023.1 --project-path=/workspaces/prj-name/PrjName.sln'
Exit code: 1
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:246)
	... 35 more
Caused by: com.jetbrains.gateway.ssh.RemoteCommandException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/workspaces/.codespaces/shared/editors/jetbrains/JetBrainsRider-2023.1 --project-path=/workspaces/prj-name/PrjName.sln'
Exit code: 1
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.anErrorOccurred(GoHighLevelHostAccessor.kt:187)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.callAndReportError(GoHighLevelHostAccessor.kt:176)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.access$callAndReportError(GoHighLevelHostAccessor.kt:32)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor$callAndReportError$1.invokeSuspend(GoHighLevelHostAccessor.kt)
	... 35 more



==== ENVIRONMENT ====

INSTALLED PRODUCTS

	


AVAILABLE MEMORY

	62.79GB



==== DIAGNOSTIC ERRORS ====

Could not get host jstack: 

Details:
An error occurred while executing command: 'get-jstack --ide-path=/workspaces/.codespaces/shared/editors/jetbrains/JetBrainsRider-2023.1 --project-path=/workspaces/prj-name/PrjName.sln'
Exit code: 1
```

**Comment by adrianbpa** [comment]
> Do you see any errors further up the logs? The jstack error happens when it tries and fails to get debug information but the real error happens earlier.

@code-asher I believe all the information available is already shown in those logs: Although the `jstack` error happens later, the main error is already shown in both @ericpaulsen's log as well as mine: It's a `com.jetbrains.gateway.ssh.deploy.DeployExceptio` in `com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:253)`. If there is any way we can collect any more information please let me know.

Thank you!

**Comment by code-asher** [comment]
Sorry for the delayed response.  If possible the rest of the logs could be helpful (I usually find them manually but I think clicking the gear icon and selecting "collect logs" or something like that also works).  I am not sure why the `host-status` command exits with 1 or what that really means so maybe some context will help.  

But this might unfortunately be a problem with Gateway itself since it is handling the deployment here.

There are some issues that look related upstream:

https://youtrack.jetbrains.com/issues/GTW?q=Exit%20code:%201%20host-status

One issue suggests it could be related to an accumulation of temp files.
