### ISSUE TITLE
Could not get host jstack

### ISSUE THREAD

**Issue by ericpaulsen** [coder/jetbrains-coder#291]
a prospect is running Gateway `2023.2` and plugin `2.5.2` and received the following error when downloading the client from jetbrains.com

```
==== FAILURES ====

The following exception failed the deployment

com.jetbrains.gateway.ssh.deploy.DeployException:

Details:

An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/88bee55d9974b_ideaIU-2023.2 --project-path=/home/coder/coder'

Exit code: 1
                at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:299)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:174)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
                at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:170)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundPrzgressCoroutineUtil.kt:160)
                at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createModal$1$1.run(BackgroundProgressCoroutineUtil.kt:205)
                at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
                at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
                at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
                at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
                at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
                at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
                at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: com.jetbrains.gateway.ssh.deploy.DeployException:

Details:

An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/88bee55d9974b_ideaIU-2023.2 --project-path=/home/coder/coder'

Exit code: 1
                at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:294)
                ... 37 more
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException:

Details:

An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/88bee55d9974b_ideaIU-2023.2 --project-path=/home/coder/coder'

Exit code: 1
                at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:292)
                ... 37 more
Caused by: com.jetbrains.gateway.ssh.RemoteCommandException:

Details:

An error occurred while executing command: 'host-status --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/88bee55d9974b_ideaIU-2023.2 --project-path=/home/coder/coder'

Exit code: 1
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.createException(GoHighLevelHostAccessor.kt:210)
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.callAndGetError(GoHighLevelHostAccessor.kt:176)
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.access$callAndGetError(GoHighLevelHostAccessor.kt:35)
                at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor$callAndGetError$1.invokeSuspend(GoHighLevelHostAccessor.kt)
                ... 37 more 

==== ENVIRONMENT ====

INSTALLED PRODUCTS

                IntelliJ IDEA         232.8660.185

AVAILABLE MEMORY

                15.16GB

==== DIAGNOSTIC ERRORS ====

Could not get host jstack:

Details:

An error occurred while executing command: 'get-jstack --ide-path=/home/coder/.cache/JetBrains/RemoteDev/dist/88bee55d9974b_ideaIU-2023.2 --project-path=/home/coder/coder'

Exit code: 1

**Comment by ericpaulsen** [comment]
resolved in the latest versions of Gateway and the plugin, 2023.2.2 and 2.6.0 respectively.

**Comment by Moortingale** [comment]
I'm also having this problem, even after upgrading to PHP version 2023.2.3.
==== DIAGNOSTIC ERRORS ====

Could not get host jstack: 

Details:
An error occurred while executing command: 'get-jstack --ide-path=/home/xxxxxxxxx/.cache/JetBrains/RemoteDev/dist/a7749167797d7_PhpStorm-232.9559.14 --project-path=/'
Exit code: 1
