### ISSUE TITLE
FileAlreadyExistsException: /Users/xxxx/.ssh

### ISSUE THREAD

**Issue by init-object** [coder/jetbrains-coder#330]
When I already have /Users/xxxx/.ssh/config file
an exception occurs

java.nio.file.FileAlreadyExistsException: /Users/xxxx/.ssh
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:753)
	at com.coder.gateway.sdk.CoderCLIManager.writeSSHConfig(CoderCLIManager.kt:306)
	at com.coder.gateway.sdk.CoderCLIManager.configSsh(CoderCLIManager.kt:196)
	at com.coder.gateway.views.steps.CoderWorkspacesStepView.onNext(CoderWorkspacesStepView.kt:624)

**Comment by init-object** [comment]
beacuse my .ssh/config link in my icloud 

$ ll ~/.ssh
lrwxr-xr-x  1 xxxx  staff    71B  9 26 14:34 /Users/xxxx/.ssh -> /Users/xxxx/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.ssh
