### ISSUE TITLE
passing a parameter to header command wont work

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/jetbrains-coder#387]
# Description

The header command behaves not exactly the same as in coder extension for VS Code. Generating an header for coder to get access to a protected site via Azure application proxy fails, because executing `sh -c` is missing quotes. This results in hanging around for ages until a timeout after 20 minutes or so.

Additional remark: using linux as operating system

## VS Code

This works as expected:

![image](https://github.com/coder/jetbrains-coder/assets/103434584/7a2b108f-a45f-4ac2-a926-903bdb719383)

## Gateway

This does not work:

![image](https://github.com/coder/jetbrains-coder/assets/103434584/78129218-a21e-47d3-9672-dc92734cf0c3)

# Example

As one can see in the example below the plugin executes `sh -c ~/bin/coder-helper header` this will not work even directly from terminal.

```
CLI exited unexpectedly with 1.

org.zeroturnaround.exec.InvalidExitValueException: Unexpected exit value: 1, allowed exit values: [0], executed command [/home/xxx/.local/share/coder-gateway/xxx/coder-linux-amd64, login, https://coder.xxx.de/, --token, o80xxxxx, --global-config, /home/xxx/.local/share/coder-gateway/coder.xxx.de/config] with environment {CODER_HEADER_COMMAND=~/bin/coder-helper header}, output was 131 bytes:
Encountered an error running "coder login"
create header transport: failed to run [sh -c ~/bin/coder-helper header]: exit status 1
	at org.zeroturnaround.exec.InvalidExitUtil.checkExit(InvalidExitUtil.java:27)
	at org.zeroturnaround.exec.WaitForProcess.call(WaitForProcess.java:114)
	at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1076)
	at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:906)
	at com.coder.gateway.cli.CoderCLIManager.exec(CoderCLIManager.kt:397)
	at com.coder.gateway.cli.CoderCLIManager.login(CoderCLIManager.kt:197)
	at com.coder.gateway.views.steps.CoderWorkspacesStepView$connect$1.invokeSuspend(CoderWorkspacesStepView.kt:520)
	at com.coder.gateway.views.steps.CoderWorkspacesStepView$connect$1.invoke(CoderWorkspacesStepView.kt)
	at com.coder.gateway.views.steps.CoderWorkspacesStepView$connect$1.invoke(CoderWorkspacesStepView.kt)
	at com.intellij.openapi.rd.util.ProgressCoroutineScopeLegacy$Companion$execute$2$1.invokeSuspend(BackgroundProgressCoroutineUtil.kt:448)
	at com.intellij.openapi.rd.util.ProgressCoroutineScopeLegacy$Companion$execute$2$1.invoke(BackgroundProgressCoroutineUtil.kt)
	at com.intellij.openapi.rd.util.ProgressCoroutineScopeLegacy$Companion$execute$2$1.invoke(BackgroundProgressCoroutineUtil.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.rd.util.ProgressCoroutineScopeLegacy$Companion$execute$2.invokeSuspend(BackgroundProgressCoroutineUtil.kt:447)
	at com.intellij.openapi.rd.util.ProgressCoroutineScopeLegacy$Companion$execute$2.invoke(BackgroundProgressCoroutineUtil.kt)
	at com.intellij.openapi.rd.util.ProgressCoroutineScopeLegacy$Companion$execute$2.invoke(BackgroundProgressCoroutineUtil.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.rd.util.ProgressCoroutineScopeLegacy$Companion.execute$intellij_platform_rd_community(BackgroundProgressCoroutineUtil.kt:446)
	at com.intellij.openapi.rd.util.BackgroundProgressCoroutineUtilKt$launchUnderBackgroundProgress$2$1.invokeSuspend(BackgroundProgressCoroutineUtil.kt:183)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:290)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:286)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:276)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createBackgroundable$1$1.run(BackgroundProgressCoroutineUtil.kt:309)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Fix

The extra parameter has to be qouted to get passed to the executable. Adding quotes to **-c** will now print the needed authorization header.

```bash
[xxx@workstation ~]$ sh -c "~/bin/coder-helper header"
authorization=bearer eyJ0e
```

**Comment by code-asher** [comment]
Strange, this seems to be coming from the Coder cli, I think?

https://github.com/coder/coder/blob/f96ce80ab9b1de2ba04b553924956dbdc1e06c49/cli/root.go#L572

The quotes might be a red herring, just a consequence of how we print the command when there is an error.

But, then, it makes no sense.  :thinking:

**Comment by MrPeacockNLB** [comment]
How can we help to fix this Issue?

**Comment by code-asher** [comment]
Ah, was it timing out then?  Although I think I would expect a code different than 1 in that case, but I am not sure.

If this is a still a problem, maybe one way to try debugging is to look at `~/.ssh/config` and try out the commands seen there.  For example, you might see something like this:

```
Host coder-jetbrains--header--test.coder.invalid
  ProxyCommand /tmp/coder-gateway/test.coder.invalid/coder-linux-amd64 --global-config /tmp/coder-gateway/test.coder.invalid/config --header-command '~/bin/coder-helper header' ssh --stdio header
  ConnectTimeout 0
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR
  SetEnv CODER_SSH_SESSION_TYPE=JetBrains
```

So as a test in this example you could run:

```
 /tmp/coder-gateway/test.coder.invalid/coder-linux-amd64 --global-config /tmp/coder-gateway/test.coder.invalid/config --header-command '~/bin/coder-helper header' list
```

Wait...could it be the single quotes?   Might be making it treat `~` literally?
